// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace LoadTest.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class OrderItem
    {
        /// <summary>
        /// Initializes a new instance of the OrderItem class.
        /// </summary>
        public OrderItem() { }

        /// <summary>
        /// Initializes a new instance of the OrderItem class.
        /// </summary>
        public OrderItem(string serialNumber = default(string), string title = default(string), string description = default(string), double? cost = default(double?), int? quantity = default(int?))
        {
            SerialNumber = serialNumber;
            Title = title;
            Description = description;
            Cost = cost;
            Quantity = quantity;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serialNumber")]
        public string SerialNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cost")]
        public double? Cost { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

    }
}
